/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_geniusgithub_mediarender_jni_PlatinumJniProxy */

#ifndef __PLATINUM_JNI_H__
#define __PLATINUM_JNI_H__
#ifdef __cplusplus
extern "C" {
#endif

void J4A_onActionReflection(int cmd, const char* value, const char* data);

#ifdef __cplusplus
}
#endif
#endif
